# **Àlgebra Linear com Python: uma breve introdução**

## Introdução

Este notebook objetiva demonstrar a resolução de problemas comuns da Álgebra Linear utilizando NumPy e SymPy.

Primeiro iremos importar as bibliotecas que iremos utilizar no decorrer deste notebook:

In [1]:
import numpy as np
import sympy
from sympy.matrices import zeros,eye,ones

## Definição

Da Álgebra linear sabemos que uma matriz A sobre um corpo K ou, simplesmente, uma matriz A (quando K estiver subentendido) é uma tabela
retangular de escalares, costumeiramente representada no formato que segue:$$A= \left[
\begin{array}{c c c}
a_{11}&\ldots& a_{1n}\\
a_{21}& \ldots& a_{2n}\\
\vdots&\ddots &\vdots\\ a_{m1}&\ldots& a_{mn}
\end{array}\right]
$$ 

Dizemos que uma matriz com m linhas e n colunas é uma matriz m $\times $ n . O par de
números $m$ e $n$ é dito o tamanho da matriz.

## Tipos especiais de matrizes

Consideremos uma matriz com $m$ linhas e $n$ colunas que denotaremos por $A_{m\times n}$. Apresentaremos brevemente algumas matrizes importantes em Álgebra Linear. Utilizaremos o construtor Matrix() da biblioteca SymPy para definir as matrizes.

1. Matriz Quadrada: matriz em que o número de linhas é igual ao número de colunas ($m=n$).

In [2]:
A = sympy.Matrix(2,2,[-1, 2, 4, 5])
A

Matrix([
[-1, 2],
[ 4, 5]])

2. Matriz Nula: matriz em que todos os elementos são nulos, ou seja, $a_{ij}=0$ para todo $i$ e $j$.

In [3]:
B = sympy.zeros(2,3)
B

Matrix([
[0, 0, 0],
[0, 0, 0]])

3. Matriz-Coluna:matriz que possui uma única coluna ($A_{m \times 1}$).

In [4]:
C = sympy.Matrix(4,1, [-1, 2, 10, 5])
C

Matrix([
[-1],
[ 2],
[10],
[ 5]])

4. Matriz-Linha: matriz com uma única linha ($A_{1 \times n}$)

In [5]:
x,y,z = sympy.symbols(['x','y','z'])  #transform string em símbolos

In [6]:
D = sympy.Matrix(1,3, [x,y,z])
D

Matrix([[x, y, z]])

5. Matriz diagonal: matriz quadrada em que qualquer elemento fora da diagonal principal é nulo, isto é, $a_{ij}=0$ para $ i \neq j$.<br>

Assim, dizemos que uma matriz quadrada S $=$$[s_{ij}]$ é diagonal se todos os seus elementos fora da diagonal principal forem
nulos. Às vezes, denotamos uma tal matriz por S $=$diag $s_{11},s_{22}, ..., s_{nn}$  onde alguns $s_{ii}$, ou todos, podem ser nulos.

In [7]:
E = sympy.diag(1, -2, -7, 4)
E

Matrix([
[1,  0,  0, 0],
[0, -2,  0, 0],
[0,  0, -7, 0],
[0,  0,  0, 4]])

5. Matriz identidade: matriz em que $a_{ij}=1$ ,  $\forall i=j$ e $a_{ij}=0$, $\forall i \neq j$. Assim, a matriz identidade, ou matriz unitária, de ordem $n$, denotada por $I{_n}$ ou, simplesmente, por $I$, é a matriz quadrada
com 1 na diagonal principal e 0 em todas as demais entradas. A matriz identidade $I$ é análoga ao escalar $1$, pois,
dada qualquer matriz $A_{m \times n}$, temos que $\mathbf{AI =IA = A}$. Para uma matriz $B_{n \times 1}$, verifica-se $\mathbf{IB=B}$

In [8]:
I = sympy.eye(4)
I 

Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

6. Matriz triangular superior: matriz quadrada em que todos os elementos abaixo da diagonal principal são nulos, ou seja, $a_{ij}=0$ se $i>j$.

In [9]:
D = sympy.Matrix(np.triu([2,-1,4],k=0))
D

Matrix([
[2, -1, 4],
[0, -1, 4],
[0,  0, 4]])

7. Matriz triangular inferior: matriz quadrada em que todos os elementos acima da diagonal principal são nulos, ou seja, $a_{ij} = 0$, $\forall i<j$.

In [10]:
F = sympy.Matrix(np.tril([[2,1,1],[1,-1,1], [1,1,2]]))
F

Matrix([
[2,  0, 0],
[1, -1, 0],
[1,  1, 2]])

8. Matriz simétrica: matriz quadrada em que $a_{ij} = a_{ji}$ para quaisquer $i,j$ e $A^{T} = A$.

In [11]:
G = sympy.Matrix(3, 3, [4, 3, -1, 3, 2, 0, -1, 0, 5])
G

Matrix([
[ 4, 3, -1],
[ 3, 2,  0],
[-1, 0,  5]])

9. Matriz Idempotente: matriz quadrada em que $A \cdot A = A$ .

In [12]:
H = sympy.Matrix(2, 2, [5, -5, 4, -4])
H

Matrix([
[5, -5],
[4, -4]])

In [13]:
H*H

Matrix([
[5, -5],
[4, -4]])

10. Matriz Ortogonal: toda matriz em que $A^{-1}=A^{T}$.

## Operações com matrizes

### Adição e multiplicação por escalar

Sejam A $=$ $a_{ij}$ e B  $=$ $b_{ij}$ duas matrizes de mesmo tamanho, digamos, m $\times $ n  . A soma de A e B, denotada por
A $+$ B, é a matriz obtida pela soma de elementos correspondentes de A e B, 
ou seja 

 $$A+B =\left[
\begin{array}{c c c}
a_{11}+ b_{11}&\ldots& a_{1n}+b_{1n}\\
a_{21}+b_{21}& \ldots& a_{2n}+b_{2n}\\
\vdots&\ddots &\vdots\\ a_{m1}+b_{m1}&\ldots& a_{mn}+ b_{mn}
\end{array}\right]
$$

O múltiplo da matriz A pelo escalar k, denotado por simplesmente $kA$, é a matriz obtida pelo produto de
cada elemento de A por k, ou seja,


$$kA=\left[ 
\begin{array}{c c c}
ka_{11}&\ldots& ka_{1n}\\
ka_{21}& \ldots& ka_{2n}\\
\vdots&\ddots &\vdots\\ ka_{m1}&\ldots& ka_{mn}
\end{array}\right]
$$

Vejamos uma implementação da soma de duas matrizes utilizando o NumPy.

Seja 
A = $\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6 
\end{bmatrix}$ e B =$\begin{bmatrix}
2 &  4 & 6\\
1 & 3 & 5  \end{bmatrix}$ iremos encontrar a matriz C, dada por $\mathrm{A+B}$. Iremos simplesmente definir $A$ e $B$ e posteriormente usar o operador $+$.

In [14]:
A = np.array([[1,2,3], [4,5,6]])
B = np.array([[2,4,6],[1,3,5]])
C = A+B

In [15]:
C

array([[ 3,  6,  9],
       [ 5,  8, 11]])

Encontrada a matriz C, iremos encontrar a matriz D, dada por kC, onde k = -2.

In [16]:
C = np.array ([[3,6,9], [5,8,11]])
k = -2
D = k*C

In [17]:
D

array([[ -6, -12, -18],
       [-10, -16, -22]])

Poderíamos resolver este mesmo problema usando a função np.dot() - utilizada para efetuar o produto matricial:

In [18]:
D = np.dot(k,C)

In [19]:
D

array([[ -6, -12, -18],
       [-10, -16, -22]])

<b>Propriedades da soma de matrizes</b> <br>
Considerando as matrizes A,B e C de mesma ordem $m x n$ temos que: 
1. $\mathbf {A} +\mathbf {B} = \mathbf{B+A} $ (comutatividade)
2. $\mathbf {A}+\mathbf{(B+C)} = \mathbf{(A+B)}+C$ (associatividade)
3. $\mathbf {A}+\mathbf{0} = \mathbf{A}$ 

Iremos demonstrar a validade de tais propriedades usando funções de Álgebra Linear do SymPy.Para tanto, definiremos três matrizes quadradas genéricas de ordem 2.

In [20]:
a11, a12, a21, a22 = sympy.symbols('a_11, a_12, a_21, a_22')
b11, b12, b21, b22 = sympy.symbols('b_11, b_12, b_21, b_22')
c11, c12, c21, c22 = sympy.symbols('c_11, c_12, c_21, c_22')
A = sympy.Matrix(2, 2, [a11, a12, a21, a22])
B = sympy.Matrix(2, 2, [b11, b12, b21, b22])
C = sympy.Matrix(2, 2, [c11, c12, c21, c22])

Vejamos as matrizes definidas:

In [21]:
A

Matrix([
[a_11, a_12],
[a_21, a_22]])

In [22]:
B

Matrix([
[b_11, b_12],
[b_21, b_22]])

In [23]:
C

Matrix([
[c_11, c_12],
[c_21, c_22]])

Da propriedade <b>1</b> temos que:

In [24]:
A+B

Matrix([
[a_11 + b_11, a_12 + b_12],
[a_21 + b_21, a_22 + b_22]])

In [25]:
B+A

Matrix([
[a_11 + b_11, a_12 + b_12],
[a_21 + b_21, a_22 + b_22]])

Então:

In [26]:
(A+B) == (B+A)

True

Da propriedade <b>2</b> temos que: 

In [27]:
A+(B+C)

Matrix([
[a_11 + b_11 + c_11, a_12 + b_12 + c_12],
[a_21 + b_21 + c_21, a_22 + b_22 + c_22]])

In [28]:
(A+B)+C

Matrix([
[a_11 + b_11 + c_11, a_12 + b_12 + c_12],
[a_21 + b_21 + c_21, a_22 + b_22 + c_22]])

In [29]:
A+(B+C) == (A+B)+C

True

Por fim, precisaremos criar uma matriz nula para verificar a última propriedade.

In [30]:
from sympy.matrices import zeros

In [31]:
zero = zeros(2,2)

In [32]:
zero

Matrix([
[0, 0],
[0, 0]])

Desta forma, podemos verificar que:

In [33]:
A+zero == A

True

<b>Propriedades da multiplicação por escalar </b> <br>
Sejam as matrizes A e B de mesma ordem e as constantes reais $k$, $k_1$, $k_2$, temos que:
1. $k(\mathbf{A+B}) = k\mathbf{A}+k\mathbf{B}$
2. $(k_1+k_2)\mathbf{A} = k_1\mathbf{A}+k_2\mathbf{A}$
3. $k\mathbf{A} = \mathbf{0} $, em que k=0

Voltando para as matrizes... Observe que ambas, A $+$ B e kA, são matrizes m $\times $ n . Podemos definir
–A $=$(–1)A e A $-$ B $=$ A $+$ (–B).
Dizemos que –A é a matriz simétrica de A e que A $-$ B é a matriz diferença de A e B. Não se define a soma de matrizes
de tamanhos distintos.

Seja A = $\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6 
\end{bmatrix}$ encontremos a matriz simétrica de A. Definiremos a matriz A e seguidamente obteremos sua matriz simétrica.

In [34]:
A = np.array([[1,2,3],[4,5, 6]])

In [35]:
-A

array([[-1, -2, -3],
       [-4, -5, -6]])

Poderíamos também ter obtido a matriz simétrica de A como segue.

In [36]:
k=-1
A_simetrica = np.dot(k,A)

In [37]:
A_simetrica

array([[-1, -2, -3],
       [-4, -5, -6]])

Vamos recuperar a matriz B definida anteriormente e calcular $\mathbf{A-B}$.

In [38]:
B = np.array([[2,4,6],[1,3,5]])

In [39]:
A-B

array([[-1, -2, -3],
       [ 3,  2,  1]])

Dadas as matrizes H = $\begin{bmatrix}
1 & 2 & 3\\
4 & -2 & -9\\
0 & -12 & -29\\
\end{bmatrix}$ e G =  $\begin{bmatrix}
11 & 0 & 0\\
41 & -21 & 0\\
0 & -1 & -2\\
\end{bmatrix}$ encontraremos a matriz J dada por J = H+G.

Utilizando NumPy obtemos o seguinte resultado:

In [40]:
H = np.array([[1, 2, 3], [4, -2, -9], [0, -12, -29]])
G = np.array([[11, 0, 0], [41, -21, 0], [0, -1, -2]])
J = H+G

In [41]:
J 

array([[ 12,   2,   3],
       [ 45, -23,  -9],
       [  0, -13, -31]])

Podemos resolver o mesmo problema com SymPy. Usaremos a função Matrix para construir as matrizes H e G. Informaremos a ordem das respectivas matrizes e passaremos uma lista contendo seus elementos.

In [42]:
H = sympy.Matrix(3, 3, [1, 2, 3, 4, -2, -9, 0, -12, -29])
G = sympy.Matrix(3, 3, [11, 0, 0, 41, -21, 0, 0, -1, -2])
J = G+H

In [43]:
J

Matrix([
[12,   2,   3],
[45, -23,  -9],
[ 0, -13, -31]])

### Transposta de uma matriz

A transposta de uma matriz A, denotada por $A^{T}$ ou $A' $, é a matriz obtida escrevendo as colunas de A, na mesma ordem, como linhas.

<b>Propriedades</b>
1. Uma matriz é simétrica se, e somente se ela é igual à sua transposta, ou seja, $\mathbf{A=A'}$.
2. $\mathbf{A''=A}$.
3. $\mathbf{(A+B)'=A'+B'}$.
4. $\mathbf{(kA)'=kA'}$, em que k é um escalar.

Seja,  I =  $\begin{bmatrix}
2 & 0 \\
-4 & 11 \\
5 &-2 \\
 6 & 0 \\
\end{bmatrix}$ então $I^{T}$ $= $ $\begin{bmatrix}
2 & -4 & 5 & 6\\   
0 &11 & -2 & 0\\
\end{bmatrix}$. Em linhas gerais, a linha de uma matriz passa a ser coluna e a coluna se torna linha. 

Dada a matriz K =  $\begin{bmatrix}
-1 & 0 & 0\\
-4 & 11  & 1 \\
5 &-2 & -9\\
 6 & 0 &7\\
\end{bmatrix}$, encontremos sua matriz transposta $K^{T}$ utilizando o NumPy.

In [44]:
K = np.array([[-1, 0, 0], [-4, 11, 1], [5, -2, -9], [6, 0, 7]])

In [45]:
K

array([[-1,  0,  0],
       [-4, 11,  1],
       [ 5, -2, -9],
       [ 6,  0,  7]])

Assim, a transposta de K é obtida como segue:

In [46]:
np.transpose(K)

array([[-1, -4,  5,  6],
       [ 0, 11, -2,  0],
       [ 0,  1, -9,  7]])

Ou

In [47]:
K.T

array([[-1, -4,  5,  6],
       [ 0, 11, -2,  0],
       [ 0,  1, -9,  7]])

Dada a matriz L =  $\begin{bmatrix}
0 & 1 & 0\\
-4 & 11  & 1 \\
5 &-2 & -9\\
 6 & 0 &7\\
 36 & 10 &57\\
\end{bmatrix}$ encontremos $L+L^{T}$ utilizando NumPy.

In [48]:
L = np.array([[0, 1, 0], [-4, 11, 1], [5, -2, -9], [6, 0, 7], [36, 10, 57]])
L

array([[ 0,  1,  0],
       [-4, 11,  1],
       [ 5, -2, -9],
       [ 6,  0,  7],
       [36, 10, 57]])

In [49]:
np.transpose(L)

array([[ 0, -4,  5,  6, 36],
       [ 1, 11, -2,  0, 10],
       [ 0,  1, -9,  7, 57]])

Neste caso, não poderemos obter $L+L^{T}$, pois $L^{T}$ não apresenta a mesma ordem de L.

In [50]:
np.transpose(L).shape, np.shape(L)

((3, 5), (5, 3))

### Multiplicação de matrizes

O produto das matrizes $A$ e $B$ é denotado por $AB$. Particularmente, iremos começar com um caso
especial.
O produto $AB$ de uma matriz linha A $=$ $[a_i]$ e uma matriz coluna B  $=$  $[b_j]$ com o mesmo número de elementos
é definido como o escalar (ou a matriz ) obtido pela soma dos produtos das entradas correspondentes, ou seja, AB= $\begin{bmatrix}
a_{1}, & a_{2}, & ...,&a_{n}\\
\end{bmatrix} $$\begin{bmatrix}
b_{1} \\ 
b_{2} \\ 
... \\  
b_{n}\\
\end{bmatrix}$ $= $$a_{1}b_{1}$+$ $$a_{2}b_{2}$$+$ ... $+$$a_{n}b_{n}$.

Enfatizamos que, nesse caso, $AB$ é um escalar (ou, então, uma matriz $1 \times 1$). Não definimos o produto AB se a
matriz linha A e a matriz coluna B possuírem um número distinto de elementos. Esta definição é particularmente importante para definição de um problema de regressão linear múltipla.

Dadas as matrizes M = $\begin{bmatrix}
7, & -4,& 5 \\
\end{bmatrix}$ e N = $\begin{bmatrix}
3 \\ 
2 \\ 
-1\\
\end{bmatrix}$ encontremos a matriz $O = M \cdot N$.

In [51]:
M = np.array([[7, -4, 5]])
N = np.array([[3],[2],[-1]])

In [52]:
M

array([[ 7, -4,  5]])

In [53]:
N

array([[ 3],
       [ 2],
       [-1]])

Para realizar a multiplicação das matrizes é necessário encontrar o número de linhas e colunas da matriz.

In [54]:
M.shape

(1, 3)

Acima vemos que nossa matriz M possui uma linha e três colunas. 

In [55]:
N.shape

(3, 1)

Acima vemos que nossa matriz N possui três linhas e uma coluna. Assim, para efetuar o produto matricial o número de colunas da primeira matriz, deve ser igual ao número de linhas da segunda matriz. Assim, a matriz O, será :

In [56]:
O = np.dot(M,N)
O

array([[8]])

Dadas as matrizes Q =  $\begin{bmatrix}
6, & -1,& 8 & 3  \\
\end{bmatrix}$ e S = $\begin{bmatrix}
4 \\ 
-9 \\ 
-2\\
5\\
\end{bmatrix}$ encontraremos a matriz P fruto de QS.

In [57]:
Q = np.array([[6, -1, 8, 3]])
S = np.array ([[4], [-9], [-2], [5]])

Verificaremos se o número de colunas de Q é igual ao número de linhas de S:

In [58]:
Q.shape[1] == S.shape[0]

True

Então a matriz P é obtida da seguinte forma:

In [59]:
P = np.dot(Q,S)
P

array([[32]])

De um modo geral, dadas A $=$ $[a_{ik}]$ e B  $=$  $[b_{kj}]$ duas matrizes tais que o número de colunas de A seja igual ao número
de linhas de B, digamos p, supomos assim que A seja uma matriz m $\times$ n e B uma matriz p $\times$ n. Então o produto AB de A e B é a matriz  m $\times$ n cuja ij-ésima entrada é dada pelo produto da i-ésima linha de A com a j-ésima coluna de B. Assim,

$\begin{bmatrix}
a_{11} & ... & a_{1p}\\   
. & ... & . \\
a_{i1}& ...&  a_{1p}\\
. & ... & . \\
a_{m1}& ...&  a_{mp}
\end{bmatrix}$
$\begin{bmatrix}
b_{11} & ... & b_{ij} & ... & b_{1n}\\
. & ... & .  & ... & . \\
. & ... & .  & ... & . \\
. & ... & .  & ... & . \\
b_{p1}& ...& b_{pj} &...& b_{pn}
\end{bmatrix}$ onde $c_{ij}$ $= $$a_{i1}b_{ij}$+$ $$a_{i2}b_{j2}$$+$ ... $+$$a_{ip}b_{pj}$.

Não definimos o produto AB quando A é uma matriz m $\times$ p e B é uma matriz com q $\times$ n com p $\neq$ q.

<b>Propriedades da Multiplicação de Matrizes</b>
1. Em geral $\mathbf{AB}\neq\mathbf{BA}$.
2. $\mathbf{AI} = \mathbf{IA} = \mathbf{A} $ (o que justifica o nome da matriz identidade)
3. $\mathbf{A(B+C)} = \mathbf{AB}+\mathbf{AC}$ (distributividade à esquerda da multiplicação)
4. $\mathbf{(A+B)C} = \mathbf{AC+BC} $ (distributividade à direita da multiplicação)
5. $\mathbf{(AB)C = A(BC)} $ (associatividade)
6. $\mathbf{(AB)' = B'A'} $
7. $\mathbf{0 \cdot A = 0}$ e $\mathbf{A \cdot 0 = 0}$

Demonstremos algumas destas propriedades utilizando matrizes genéricas.

In [60]:
from sympy.matrices import eye
a11, a12, a21, a22 = sympy.symbols('a_11, a_12, a_21, a_22')
b11, b12, b21, b22 = sympy.symbols('b_11, b_12, b_21, b_22')
c11, c12, c21, c22 = sympy.symbols('c_11, c_12, c_21, c_22')
A = sympy.Matrix(2, 2, [a11, a12, a21, a22])
B = sympy.Matrix(2, 2, [b11, b12, b21, b22])
C = sympy.Matrix(2, 2, [c11, c12, c21, c22])
I = eye(2)
zero = zeros(2)

Respectivamente temos as matrizes A,B,C,I e a matriz nula:

In [61]:
display(A)
display(B)
display(C)
display(I)
display(zero)

Matrix([
[a_11, a_12],
[a_21, a_22]])

Matrix([
[b_11, b_12],
[b_21, b_22]])

Matrix([
[c_11, c_12],
[c_21, c_22]])

Matrix([
[1, 0],
[0, 1]])

Matrix([
[0, 0],
[0, 0]])

2. $\mathbf{AI} = \mathbf{IA} = \mathbf{I} $ 

In [62]:
A*I == I*A

True

3. $\mathbf{A(B+C)} = \mathbf{AB}+\mathbf{AC}$

In [63]:
A*(B+C)

Matrix([
[a_11*(b_11 + c_11) + a_12*(b_21 + c_21), a_11*(b_12 + c_12) + a_12*(b_22 + c_22)],
[a_21*(b_11 + c_11) + a_22*(b_21 + c_21), a_21*(b_12 + c_12) + a_22*(b_22 + c_22)]])

In [64]:
A*B+A*C

Matrix([
[a_11*b_11 + a_11*c_11 + a_12*b_21 + a_12*c_21, a_11*b_12 + a_11*c_12 + a_12*b_22 + a_12*c_22],
[a_21*b_11 + a_21*c_11 + a_22*b_21 + a_22*c_21, a_21*b_12 + a_21*c_12 + a_22*b_22 + a_22*c_22]])

In [65]:
sympy.expand(A*(B+C)) == A*B+A*C

True

4. $\mathbf{(A+B)C} = \mathbf{AC+BC} $

In [66]:
(A+B)*C

Matrix([
[c_11*(a_11 + b_11) + c_21*(a_12 + b_12), c_12*(a_11 + b_11) + c_22*(a_12 + b_12)],
[c_11*(a_21 + b_21) + c_21*(a_22 + b_22), c_12*(a_21 + b_21) + c_22*(a_22 + b_22)]])

In [67]:
A*C+B*C

Matrix([
[a_11*c_11 + a_12*c_21 + b_11*c_11 + b_12*c_21, a_11*c_12 + a_12*c_22 + b_11*c_12 + b_12*c_22],
[a_21*c_11 + a_22*c_21 + b_21*c_11 + b_22*c_21, a_21*c_12 + a_22*c_22 + b_21*c_12 + b_22*c_22]])

In [68]:
sympy.expand((A+B)*C) == A*C+B*C

True

5. $\mathbf{(AB)C = A(BC)} $

In [69]:
(A*B)*C

Matrix([
[c_11*(a_11*b_11 + a_12*b_21) + c_21*(a_11*b_12 + a_12*b_22), c_12*(a_11*b_11 + a_12*b_21) + c_22*(a_11*b_12 + a_12*b_22)],
[c_11*(a_21*b_11 + a_22*b_21) + c_21*(a_21*b_12 + a_22*b_22), c_12*(a_21*b_11 + a_22*b_21) + c_22*(a_21*b_12 + a_22*b_22)]])

In [70]:
A*(B*C)

Matrix([
[a_11*(b_11*c_11 + b_12*c_21) + a_12*(b_21*c_11 + b_22*c_21), a_11*(b_11*c_12 + b_12*c_22) + a_12*(b_21*c_12 + b_22*c_22)],
[a_21*(b_11*c_11 + b_12*c_21) + a_22*(b_21*c_11 + b_22*c_21), a_21*(b_11*c_12 + b_12*c_22) + a_22*(b_21*c_12 + b_22*c_22)]])

In [71]:
sympy.expand((A*B)*C) == sympy.expand(A*(B*C))

True

6. $\mathbf{(AB)' = B'A'} $

In [72]:
(A*B).transpose() == B.transpose()*A.transpose()

True

7. $\mathbf{0 \cdot A = 0}$

In [73]:
zero*A

Matrix([
[0, 0],
[0, 0]])

Iremos abordar outros exemplos numéricos de multiplicação de matrizes utilizando o NumPy.

Encontraremos XY sendo X = $\begin{bmatrix}
1 & 3 \\   
2 &-1\\
\end{bmatrix}$ e Y =  $\begin{bmatrix}
2 & 0 & -4 \\   
5 &-2 & 6 \\
\end{bmatrix}$

Devemos inicialmente verificar a condição do produto matricial.

In [74]:
X = np.array([[1, 3], [2, -1]])
Y = np.array([[2, 0, -4], [5, -2, 6]])
X.shape[1] == Y.shape[0]

True

In [75]:
np.dot(X,Y)

array([[ 17,  -6,  14],
       [ -1,   2, -14]])

### Traço de uma matriz 

O traço de uma matriz quadrada A, denotado por tr(A), é a soma dos elementos da diagonal principal, a saber, $ tr\mathbf{(A)}= a_{11}+a_{22}+a_{33}+...+a_{nn}$

<b>Propriedades</b>
1. $tr\mathbf{(A+B)} = tr\mathbf{(B+A)}$
2. $tr\mathbf{(\alpha \cdot A)} = \alpha \cdot tr\mathbf{(A)}$, com $\alpha \in \mathbb{R} $
3. $tr\mathbf{(A)} = tr\mathbf{(A')} $
4. $tr\mathbf{(I_{n})} = n$
5. $tr\mathbf{(AB)} = tr\mathbf{(BA)}$

A partir das matrizes definidas a seguir, calcularemos o traço utilizando SymPy e NumPy. Nosso primeiro exemplo será com uma matriz Identidade $I_{2}$. Para construir uma matriz identidade no NumPy podemos utilizar o comando: np.eye(). Por exemplo, a matriz 

In [76]:
F = np.eye(2)
F

array([[1., 0.],
       [0., 1.]])

O traço da matriz F é dado pela função np.trace(). Assim, 

In [77]:
np.trace(F)

2.0

Ou,

In [78]:
F.trace()

2.0

Definiremos uma matriz identidade 10 $\times$ 10 e calcularemos seu traço.

In [79]:
O = np.eye(10) 

In [80]:
O

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [81]:
np.trace(O)

10.0

Definiremos uma matriz diagonal e em seguida obteremos seu traço utilizando o NumPy

In [82]:
P = np.diag(np.arange(1,6))
P

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [83]:
P.trace()

15

Para recuperar a diagonal principal podemos utilizar o método np.diagonal() .

In [84]:
np.diagonal(P)

array([1, 2, 3, 4, 5])

Ou ainda, acessando como um método do objeto criado:

In [85]:
P.diagonal()

array([1, 2, 3, 4, 5])

Para encontra a diagonal secundária, podemos utilizar o método: np.flipl().

In [86]:
np.diagonal(np.fliplr(P))

array([0, 0, 3, 0, 0])

Definiremos agora duas matrizes genéricas A e B utilizando o SymPy, em seguida calcularemos o traço associado a cada matriz.

In [87]:
from sympy.abc import a, b, c, d,e,f,g,h
A = sympy.Matrix(2, 2, [a, b, c, d])
B = sympy.Matrix(2, 2, [e, f, g, h])

In [88]:
A

Matrix([
[a, b],
[c, d]])

In [89]:
B

Matrix([
[e, f],
[g, h]])

Traço de A:

In [90]:
sympy.trace(A)

a + d

Traço de B:

In [91]:
sympy.trace(B)

e + h

Vamos verificar as propriedade (1), (3) e (5) definidas anteriormente.

$tr\mathbf{(A+B)} = tr \mathbf{(B+A)} $ 

In [92]:
sympy.trace(A+B)

a + d + e + h

In [93]:
sympy.trace(B+A)

a + d + e + h

$tr\mathbf{(A)} = tr\mathbf{(A')}$

In [94]:
sympy.trace(A) == sympy.trace(A.transpose())

True

$tr\mathbf{(AB)} = tr\mathbf{(BA)}$

Temos que $\mathbf{AB}$:

In [95]:
A*B

Matrix([
[a*e + b*g, a*f + b*h],
[c*e + d*g, c*f + d*h]])

In [96]:
B*A

Matrix([
[a*e + c*f, b*e + d*f],
[a*g + c*h, b*g + d*h]])

In [97]:
sympy.trace(A*B) == sympy.trace(B*A)

True

### Determinante

Podemos pensar no determinante como um número associado a uma matriz quadrada $A_{m \times n}$. Denotamos $\det A$.

$$\left| \begin{array}{cccc}
a_{11} & a_{12} & \ldots & a_{1n}\\
a_{21} & a_{22} & \ldots & a_{2n}\\
\vdots & \vdots & \ddots & \vdots\\
a_{n1} & a_{n2} & \ldots & a_{nn}\\
\end{array}
\right|$$

Calculemos o determinante de uma matriz usando o NumPy.

Dada a matriz V = $\begin{bmatrix}
1 & 2 & 3 & 4\\
4& 3 & 2 & 1\\
0 & 2 & 4  & 6 \\
 5 & 7 & 9 & 11 \\
\end{bmatrix}$ encontremos det (V).

Basta utilizar a função np.linalg.det()

In [98]:
V=np.array([[1, 2, 3, 4], [4, 3, 1, 1], [0, 2, 4, 6], [5, 7, 9, 1]])

In [99]:
round (np.linalg.det(V))

-20

### Matrizes invertiveis ou não singulares

Uma matriz quadrada $A$ é dita invertível, ou não singular, se existir uma matriz $B$ tal que
$AB = BA = I$ onde $I$ é a matriz identidade. Uma tal matriz $B$ é única. 

Dizemos que uma tal matriz $B$ é a inversa de $A$ e a denotamos por $A^{-1}$.Observe que a relação que define a inversa é
simétrica; ou seja, se $B$ for a inversa de $A$, então $A$ será a inversa de $B$.

Suponha que A =  $\begin{bmatrix}
2 & 5 \\   
1 & 3\\
\end{bmatrix}$ e B  =  $\begin{bmatrix}
3 & -5 \\   
-1 & 2\\
\end{bmatrix}$, verifiquemos se estas matrizes admitem inversa.

In [100]:
A= np.array ([[2,5],[1,3]])
B = np.array ([[3,-5], [-1,2]])

In [101]:
np.dot(A,B)

array([[1, 0],
       [0, 1]])

In [102]:
np.dot(B,A)

array([[1, 0],
       [0, 1]])

Assim, B é inversa de A e A é inversa de B.

Determinemos a inversa da matriz Z =  $\begin{bmatrix}
3 & 4 \\   
1 & 0\\
\end{bmatrix}$

In [103]:
Z = np.array([[3,4],[1,0]])

In [104]:
np.linalg.inv(Z)

array([[ 0.  ,  1.  ],
       [ 0.25, -0.75]])

### Sistemas Lineares 

De uma maneira geral, denomina-se sistema linear de m equações e n incógnitas $x_{1}, x_{2},..., x_{n}$ a todo sistema linear da forma :$\begin{cases}
a_{11}x_{1}+a_{12}x_{2}+...+a_{1n}x_{n}=b_{1} \\
a_{21}x_{1}+a_{22}x_{2}+...+a_{2n}x_{n}=b_{2} \\
..............................\\
a_{m1}x_{1}+a_{m2}x_{2}+...+a_{mn}x_{n}=b_{m}\\
\end{cases}$ em que $a_{11}, a_{12},..., a_{1n}, b_{1}, b_{2}, ..., b_{m}$ são números reais. 

Matriz associadas a um sistema linear:

Seja o sistema linear de m equações e n incógnitas $\begin{cases}
a_{11}x_{1}+a_{12}x_{2}+...+a_{1n}x_{n}=b_{1} \\
a_{21}x_{1}+a_{22}x_{2}+...+a_{2n}x_{n}=b_{2} \\
..............................\\
a_{m1}x_{1}+a_{m2}x_{2}+...+a_{mn}x_{n}=b_{m}\\
\end{cases}$

Desse sistema, destacamos as seguintes matrizes:
- matriz completa do sistema 
$\begin{bmatrix}
a_{11} & a_{12} & ... & a_{1n} &b_{1}\\
a_{21} & a_{22} & ... & a_{2n} & b_{2}\\
... & ... & ... & ...&....\\
a_{n1} & a_{n2} & ... & a_{nn}&b_{1m}\\
\end{bmatrix}$


- matriz incompleta do sistema 
$\begin{bmatrix}
a_{11} & a_{12} & ... & a_{1n}\\
a_{21} & a_{22} & ... & a_{2n}\\
... & ... & ... & ...\\
a_{n1} & a_{n2} & ... & a_{nn}\\
\end{bmatrix}$

Consideremos ainda as seguintes matrizes-colunas assosciadas ao sistema:
X = $\begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots\\
x_{n}\\
\end{bmatrix}$    $\space$, B = $\begin{bmatrix}
b_{1} \\
b_{2} \\
\vdots\\
b_{m}\\
\end{bmatrix}$

Multiplicando - se a matriz incompleta pela matriz das incognitas, obtemos a matriz dos temos independentes:

$$\begin{bmatrix}
a_{11} & a_{12} & ... & a_{1n}\\
a_{21} & a_{22} & ... & a_{2n}\\
... & ... & ... & ...\\
a_{n1} & a_{n2} & ... & a_{nn}\\
\end{bmatrix}\cdot \begin{bmatrix}
x_{1} \\
x_{2} \\
\vdots\\
x_{n}\\
\end{bmatrix}=\begin{bmatrix}
b_{1} \\
b_{2} \\
\vdots\\
b_{m}\\
\end{bmatrix}$$

Denominamos então que o modelo acima é a forma matricial do sistema linear.
Em notação simplificada temos:  $A \cdot X = B $.
Se a matriz incompleta do sistema for uma matriz quadrada, o seu determinante D$_{A}$ é dito determinante do sistema. 
Se D$_{A}$ $\neq$ 0 então a matriz A é invertivel, isto é, existe A$^{-1}$, inversa de A. 
Se D$_{A}$ $\neq$ 0, o sistema admite solução única e , portanto, é possível e determinado.
                
                

Representemos o sistema $\begin{cases}
3a-7b=1\\
5a+2b=4 \\
\end{cases}$ na forma matricial e encontremos sua solução.

In [105]:
A = np.array ([[3, -7], [5, 2]])
B = np.array([[1], [4]])

In [106]:
X = (np.linalg.solve(A, B))

In [107]:
X  #solução do sistema

array([[0.73170732],
       [0.17073171]])

## <b>Exercícios <b/>

1. Encontre WI sendo W = $\begin{bmatrix}
1 & 3 & 0 & 20\\   
2 &-1 & 10 & 13\\
3 & 4 & 10 & 0\\
4 & 9 & -1 & 0 \\
\end{bmatrix}$ e I =  $\begin{bmatrix}
2 & 0 \\
-4 & 11 \\
5 &-2 \\
 6 & 0 \\
\end{bmatrix}$

2. Construa uma matriz $5 \times 5$ e encontre traço, diagonal principal e secundária. 

3. Crie uma matriz $2 \times 2$ somente com elementos pares e calcule seu determinante.

4. Represente os sistemas abaixo  na forma matricial e encontre as respectivas soluções.

a) $\begin{cases}
2x+y=5\\
x-3y=0 \\
\end{cases}$ 

b)$\begin{cases}
2a+b+c=-1\\
a+c=0 \\
-3a+5b-c=2\\
\end{cases}$ 

c) $\begin{cases}
x+y+z+t=2\\
x-y-2z-3t=5 \\
2x+y-3z+t=-9\\
3x-y-z+t=6\\
\end{cases}$ 

5.  Determine a inversa das matrizes: 
<br>
a) H =  $\begin{bmatrix}
1 & 0 \\   
3 & 0\\
\end{bmatrix}$
<br>
b) I = $\begin{bmatrix}
1 & 0 & 0\\   
1 & 3 & 1\\
1 & 2 & 0\\
\end{bmatrix}$

*Todos os conceitos, proposições e teoremas aqui apresentados foram retirados do livro cujo autor é Seymour Lipschutz e/ou Simon e Blume 